#name: Bulid docker image and push to Docekr Hub 

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: my-note-app

jobs:
    Build_Docker_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: login to Docker Hub
              uses: docker/login-action@v3
              with: 
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_USERPASSWORD}}

            - name: Test Docker login
              run: docker info

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

            - name: Push the Docker image to docker hub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

            - name: Deploy with the docker compose
              run: |
                docker-compose down
                docker-compose up

            