#name: Bulid docker image and push to Docekr Hub 

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: my-note-app

jobs:
    Build_Docker_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: login to Docker Hub
              uses: docker/login-action@v3
              with: 
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_USERPASSWORD}}

            - name: Test Docker Login
              run: docker info
            
            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

            - name: Push the Docker image to docker hub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                driver: docker-container  # Enables caching support
                buildkitd-flags: --debug

            - name: Build and push Docker image with cache
              uses: docker/build-push-action@v5
              with:
                 context: .
                 push: true
                 tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
                 cache-from: type=gha
                 cache-to: type=gha,mode=max

            - name: Install Docker Compose
              run: |
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
                docker-compose version

            - name: Deploy with the Docker compose
              run: |
                docker-compose down
                docker-compose pull
                docker-compose up

            